### PR TITLE
Add B9S support

### PR DESCRIPTION
**Pull request by Jerry-Shaw**
OK, here it is. B9S support added in one commit. Compiled and test. But need more tests.

### CODE REVIEW

**Comment by d0k3** [comment]
A git rebase would have also worked :). Can you properly test it, maybe ask some other people to test, too? You could - for example - post a test build on GBAtemp. Once testing is finished, comment here, I'll take that pull requuest, maybe even do a new release.

**Comment by Jerry-Shaw** [comment]
I only have two friends tested building RedNAND, and using Luma to boot from it. All is OK under B9s. As for other binaries, they can be compiled successfully, but haven't been tested on the functions yet.

**Comment by Jerry-Shaw** [comment]
I'll post to GBATemp later, looking for more tests.

posted here:
http://gbatemp.net/threads/emunand9-with-b9s-support-need-tests-and-reports.483746/

**Comment by Jerry-Shaw** [comment]
Emm... As for new release, I do have some wishes on D9, E9 and GM9.
Can we just make the three share the same path for support files, output directory, etc?
I use D9 and GM9 a lot, but I need to create "files9" for D9 and E9, and need another "gm9" folder for GM9. Place the support files in both of the paths. 
When backup NAND, D9 and E9 can use the backup files extracting from each other, but cannot go to the default output path of GM9.
GM9 is powerful enough to do everything.
And yes, support files should be put separately in a folder, not with the output or input files. 
Could the three use some path like "/files9/support" for support files and "/files9/output" for default input/output path, so that they can share the files?

**Comment by d0k3** [comment]
GM9 paths won't be changed anymore - would only lead to confusion. GM9 does, however, accept aeskeydb.bin, seeddb.bin, encTitlekeys.bin and decTitlekeys.bin from `0:/files9` (same as those legacy tools). As for backups... just do your own script that puts these backups where you want them, done.

**Comment by Jerry-Shaw** [comment]
GM9 is OK, it can go everywhere. But could we set the default output path for D9 and E9 to some separate directory different from the support files?
Every time I extract the tickets, and the system files for friends, the files mixed.  : (
But it is OK to keep like this. This kind of job won't be much anyway.

**Comment by d0k3** [comment]
Well, that, again, would break some older tutorials, which I'd rather not do. Seriously, use GM9 for that stuff. It  is more easy than ever, and the new scripting engine allows you to automate a shitton of stuff.

**Comment by d0k3** [comment]
Ah, I almost forgot about that one. @Jerry-Shaw - does that work and is it tested?

I'm not too happy with the new output paths. If it works and I should take it over, we'd need to discuss that.

Besides, GM9 now also supports creating Multi EmuNANDs, right there, on the console.

**Comment by Jerry-Shaw** [comment]
Hi, @d0k3 . 
I am sorry for the new paths, I was just using for myself. Forgot to do it on my local PC rather than uploaded to github, really sorry for that. It will be good to change them back (And your Decrypt9WIP as well, but did not pull request, sorry for that again. Same output path and support path stored files all messed up when doing some title ticket work).

Tested, and works. Backup (emu/sys)NAND to file, then restore, create and format were tested.

Yep, I had my N3DS closed for about a year, playing NS now. 
Till yesterday, I updated all my develop environment, D9 and E9 were broken when compiling under new devkitARM. Shows "blx r3" is not supported by selected ARM CPU under the latest devkitARM. Don't know how to fix it, had only to delete those old entry points. Up till now, all is good for two days.

Hope you don't mind of my new paths. @_@

**Comment by Jerry-Shaw** [comment]
I should revert back the path commit, wait a minute. ^_^

**Comment by Jerry-Shaw** [comment]
I need to learn GM9 scripts now, haha.

**Comment by d0k3** [comment]
Merged. Still, GM9 is recommended to do this. @Jerry-Shaw - well, the EmuNAND setup is a little complicated, so it is not supported by scripting yet. You will need to do it via the HOME menu.

**Comment by Jerry-Shaw** [comment]
I have seen the GM9 HOME menu of format SD option for EmuNAND and RedNAND, and even better than EmuNAND9 can do. But did not find clone SYS to Emu yet.
BTW, are there any guide telling us what folder it is under NAND data? Some function like D9 can do, dump system files, tickets and inject. etc?

**Comment by d0k3** [comment]
Clone is an option after the format. You get a prompt offering it.

Otherwise, to do it after the format, at any time, just copy the SysNAND `S:/nandmin.bin` to the EmuNAND `E:/` drive.

In the GM9 nightly, there is the GM9 Megascript included, which automates a lot of the stuff that was earlier done by D9 plus some more.

**Comment by Jerry-Shaw** [comment]
Tried it today with GM9, feels good. All steps are clear to follow.

**Pull request merged**
